### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by Tander** [J-Dill/NoMoWanderer#1]
Testen on clean minecraftforge:28.1.106 and nomowanderer-1.0

Caused by: net.minecraftforge.fml.ModLoadingException: NoMoWanderer has class loading errors
ยง7Attempted to load class net/minecraft/client/renderer/tileentity/TileEntityRenderer for invalid dist DEDICATED_SERVER

Crashlog:
https://hatebin.com/qqtdgdnlsj

**Comment by J-Dill** [comment]
Hey @Tander, thank you for pointing this out! I'm looking into this issue now.

**Comment by J-Dill** [comment]
@Tander The crash has now been fixed; there is no longer a crash when starting up a server that includes this mod. A new version of the mod has been released (v1.1), which you can get from the releases tab here on GitHub, through the Twitch Launcher, or Curse Forge directly.

I am closing this issue as it seems to be fixed.
