### ISSUE TITLE
Mod has stopped functioning in latest release of ATM8 (1.0.19b)

### ISSUE THREAD

**Issue by zrieprakis** [J-Dill/NoMoWanderer#10]
Noticed that the mod has no effect in the latest release of ATM8.  Not sure if anyone has found a mod interaction issue yet.  Sign, pendant, and rug do nothing.

**Comment by cosmoderp** [comment]
Only the sign does not work.  I tested several times and the rug works to capture the trader just fine.

**Comment by zrieprakis** [comment]
Good to know.  May have been my testing, then.  I was using a trader spawn egg to test.  If the rug still works, a trader "trap" could be set up as a workaround.  Thanks.

**Comment by J-Dill** [comment]
I do indeed see that it is not working in ATM8 1.0.19b. I am checking now to see if it happens when it is just NoMoWanderer, or if it is due to some interaction with other mods within ATM8.

**Comment by J-Dill** [comment]
It is something with a Forge update that has broken the ability to block the spawns. Looking into if there is a way to fix this or if it is a bug within Forge instead.

**Comment by J-Dill** [comment]
Issue has been fixed with latest release (1.3.7)

@zrieprakis @cosmoderp Thank you two for the early warning that things were awry with the mod. Would've taken a while longer for me to notice something changed on Forge's side that broke the logic of the Sign and Talisman.
