### ISSUE TITLE
Llama still spawning

### ISSUE THREAD

**Issue by d3milord** [J-Dill/NoMoWanderer#11]
mod version: 1.3.7
minecraft version: 1.19
modpack: ATM8

After the last update the Trader spawn event is correctly working, but the llama are still spawning.
To disable them you need to add the entity id in the toml config.

`
entityWatchList = ["minecraft:wandering_trader", "minecraft:trader_llama", "rats:plague_doctor", "supplementaries:red_merchant"]
`

**Comment by J-Dill** [comment]
@d3milord Thanks for bringing this to my attention. I have added the llama to the list be default now. Will have to look into a better solution, but the way they spawn the Wandering Trader has changed to make it harder to alter, so this will do for now.

For those seeing this later on, either delete the `nomowanderer-common.toml` for it to be re-created on the next start of the game, or manually add the "minecraft:trader_llama" entry to the `entityWatchList` option.
