### ISSUE TITLE
NoMoWonderer + IDAS

### ISSUE THREAD

**Issue by aNinjin** [J-Dill/NoMoWanderer#12]
Hello!

I have encountered a crash involving the Bearclaw Inn structure in Integrated Structures and Dungeons. Not too sure who to report it to but I thought since it has nothing to do with the structure itself and more to do with the wanderes I will report it here.

If you think this is an IDAS issue, let me know so I can send it over to them instead.

Here's the crash log:

[crash-2023-06-23_20.41.58-server.txt](https://github.com/J-Dill/NoMoWanderer/files/11854429/crash-2023-06-23_20.41.58-server.txt)

Thanks!

**Comment by J-Dill** [comment]
@aNinjin Thank you for the notification! I have looked into this and indeed found it to be on NoMoWanderer's side. I have just pushed a new version of the mod that should alleviate this issue for 1.19.2
