### ISSUE TITLE
[Conflict] crash: NoMoWander has a conflict with Brutal Bosses

### ISSUE THREAD

**Issue by CKY-** [J-Dill/NoMoWanderer#13]
There is a crash with Brutal Bosses
https://www.curseforge.com/minecraft/mc-mods/brutal-bosses-dungeon
and 
https://www.curseforge.com/minecraft/mc-mods/nomowanderer
 [https://gist.github.com/CKY-/b3a0d5e4cb09cd3d9a8c40fc53abbfa9](https://gist.github.com/CKY-/b3a0d5e4cb09cd3d9a8c40fc53abbfa9)
 Versions:
 forge-1.19.2-43.2.14
 nomowanderer-1.19.2_1.3.10
 brutalbosses-1.19.2-6.3
 
 This was hard to track down the only way it happens is if you go to the end at an end city that spawns a wandering trader 
 the game will lock up and stop rendering all blocks with no error output 
 
 the only way i found it was to put it on a server and teleport around until I found a wandering trader boss then watchdog kicked in 
 
 I have posted this to BOTH mod issue trackers 
 https://github.com/someaddons/dungeonbosses/issues/61

**Comment by J-Dill** [comment]
@CKY-  Thank you for the notification! I have looked into this and indeed found it to be on NoMoWanderer's side. I have just pushed a new version of the mod that should alleviate this issue for 1.19.2
