### ISSUE TITLE
[Crash] NoMoWander has crashed

### ISSUE THREAD

**Issue by CKY-** [J-Dill/NoMoWanderer#15]
Hi, again. thank you for your reply on the last error report that I sent in.

I have another one for you BUT I dont know if this one's entirely on you. I have to suspect that it may not be. Again this only showed up with a server and watchdog got involved works great in single player. 
 
I have been looking for other ways to upload logs but it seems that none of them can read the mixin data so gist it is 
[https://gist.github.com/CKY-/ee32c0bb12c2d8bc736c7f5c311c9709](https://gist.github.com/CKY-/ee32c0bb12c2d8bc736c7f5c311c9709)

Minecraft version: 1.19.2
Java version: 17.0.7
Forge version: 43.2.21

[nomowanderer-1.19.2_1.3.11](https://www.curseforge.com/minecraft/mc-mods/nomowanderer)

[supplementaries-1.19.2-2.3.20](https://www.curseforge.com/minecraft/mc-mods/supplementaries)

[More Babies-forge-1.19.1-1.0.0](https://www.curseforge.com/minecraft/mc-mods/more-babies)

[YungsBetterDesertTemples-1.19.2-Forge-2.2.2](https://legacy.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)

thank you in advance for taking a look at this and any insight you may have.

**Comment by J-Dill** [comment]
Hey @CKY-, thanks for the info! Do you happen to know what you were doing at the time or what may have happened when this crash occurred? I can see in the log it is indeed related to my mod taking a while to do something, but I am not sure what initially caused it?

Also, what did you have the config for the mod set to when this occurred? If you had one of the *Radius settings high that makes me think I should lower the max value.

**Comment by CKY-** [comment]
Thank you for getting back to me. We were headed to a village, the config for nomorewander is default. I have not seen a reason to change it yet
```

[general]
	#'true' to disable all spawns of entities in <entityWatchList> Ignores <radius>.
	disableSpawns = false
	#A list of 'modid:entityName' entries used for the various functions of this mod.
	entityWatchList = ["minecraft:wandering_trader", "minecraft:trader_llama", "rats:plague_doctor", "supplementaries:red_merchant"]

[noSolicitingSign]
	#Entities from <entityWatchList> that spawn within <signRadius> (in chunks)
	#around a No Soliciting Sign will be prevented from spawning.
	#Range: 1 ~ 12
	signRadius = 6

[spawnCap]
	#Radius used for the <spawnCap>.
	#Range: 1 ~ 12
	spawnCapRadius = 6
	#Maximum amount of each entity in the <entityWatchList> that is allowed within
	#<spawnCapRadius> of its own entity type. Set to '0' to disable.
	#Range: > 0
	spawnCap = 0

[talisman]
	#Entities from <entityWatchList> that spawn within <talismanRadius> (in chunks)
	#around a player with a No Soliciting Talisman will be prevented from spawning.
	#Range: 1 ~ 12
	talismanRadius = 6

[traderRug]
	#Entities from <entityWatchList> that spawn within <rugRadius> (in chunks)
	#around a Trader Rug will instead spawn on the Trader Rug.
	#Range: 1 ~ 12
	rugRadius = 6
```
the reason that I included Desert Temples is because there may have been a baby wander that is a boss mob. the same issue that was with the end. I have seen them in the overworld but not on a server yet, More Babies adds a wandering traders, that are babies and this could be a simple compatibility issue. how ever, I have not seen this happen anywhere but a server. so it could be as you are thinking, we can try to lower the max value of the *Radius settings. 
I can have the servers set one to 4 and one to 5 and see if the crash occurs also can try a few summon commands and see what happens? helping diagnose this would be my pleaser. just need to know what you think the best COA is.

**Comment by J-Dill** [comment]
@CKY- Thanks for the additional info; I have been able to look at this here and there for some time now and my best guess is that this is related to a structure that another mod is spawning. Within the structure may be many Wandering Traders, and my mod does a decent amount of checking for each trader. I am still working on this.

**Comment by J-Dill** [comment]
Still working on this; to fix this issue will take a rework of the mod from the ground-up so this may take a little while.

**Comment by AngellusMortis** [comment]
In case you are still looking for more data. This is happening on 1.20.1 with version 1.6.0. The other mod that is spawning wandering traders is [Moog's Voyager Structures](https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures). I verified it was NoMoWanderer by removing it, rendering the bad chunk and then locating the wandering trader manually. The structure is just this little cart with a wandering trader. [Explorer's Compass](https://www.curseforge.com/minecraft/mc-mods/explorers-compass) was really helpful in locating it.

(also, thanks for the update on your working on it, this issue does not seriously negatively impact me anyways since I am using chunky to pregen stuff, just remove NoMoWanderer, pregen, and add it back)

![image](https://github.com/J-Dill/NoMoWanderer/assets/490848/cbf1aedf-1055-4088-bc8e-cc1f0ffc11b7)

**Comment by J-Dill** [comment]
This should all be good to go now in the latest 1.19.2 version of NoMoWanderer: 1.3.12
