### ISSUE TITLE
Wearing the talisman results in invisible wadering trader.

### ISSUE THREAD

**Issue by DexLuther** [J-Dill/NoMoWanderer#17]
The mod is part of the Direwolf20 1.20.1 version 1.8.0 modpack. Using default settings (unsure if these were changed by the modpack creators). 

Crafting and wearing the talisman in a curio "charm" slot results in the wandering trader still showing up, but he is invisible and makes all his usual annoying noises.

**Steps to reproduce:**
1. Download and install FTB Presents Direwolf20 1.20.1 Version 1.8.0 (latest version as of writing).
2. Create or load a world.
3. Craft the Anti-Solicitor Talisman.
4. Equip the talisman in a Curio Charm Slot.
5. Wait for the Wandering Trader to spawn.

**Expected Result:**
- The Wandering Trader doesn't spawn near the player.

**Actual Result:**
- The Wandering Trader spawns near the player or spawns the specified 6 chunks away and then wanders over to the player.
- The Wandering Trader is invisible despite it being daytime, and can still be heard.

**Note:**
- Since The Wandering Trader is invisible, it's impossible to tell if he spawned near the player or further away and wandered over.
- If the Trader spawned further away and was able to wander over, it seems to invalidate the purpose of blocking the trader.

**Comment by Kataiser9** [comment]
Having the same problem, but with the sign rather than the talisman.

I have no idea going on but I don't think it's just a simple invisibility effect. The trader and his llamas don't show up on PneumaticCraft's entity tracker, and even if I walk around the apparent source of the noise swinging wildly, I don't hit anything. Very odd.

**Comment by DexLuther** [comment]
> Having the same problem, but with the sign rather than the talisman.
> 
> I have no idea going on but I don't think it's just a simple invisibility effect. The trader and his llamas don't show up on PneumaticCraft's entity tracker, and even if I walk around the apparent source of the noise swinging wildly, I don't hit anything. Very odd.

When the trader is invisible, I don't think you can hit them. They are definitely around though. He trampled my farm a bunch of times, so I stopped using the talisman and just went back to the good old sword to the back.

Only one can spawn at a time, right? I think I'm just going to lead him away and trap him in some dirt. As long as he doesn't spawn, another one hopefully won't show up.

**Comment by Kataiser9** [comment]
You can definitely hit them while they're "normally" invisible - I've killed several invisible traders before I used this mod. Interesting about the farm trampling, though.

**Comment by DexLuther** [comment]
> You can definitely hit them while they're "normally" invisible - I've killed several invisible traders before I used this mod. Interesting about the farm trampling, though.

I just noticed. There's a game rule when creating a world to turn off the wandering trader all together. You can change it after the fact by doing `/gamerule doTraderSpawning false`. Peace and quiet finally.

**Comment by J-Dill** [comment]
This is now fixed in the latest version of the mod. If the Direwolf pack updates to use the latest 1.20.1 version of this mod it should no longer see the invisible Wandering Trader.
