### ISSUE TITLE
Crashing with a mod Simply Tea installed?

### ISSUE THREAD

**Issue by Giintaras** [J-Dill/NoMoWanderer#2]
Hello, I've encountered crash while still in fml loader screen. I think it may be a conflict with Simply Tea? Sorry, I have no experience in understanding crash-reports, but that's what I thought. Here is the link to pastebin: https://pastebin.com/GYwu46Gv

This issue occurs when both mods present. Will also post this on Simply Tea.

**Comment by J-Dill** [comment]
Hello @Giintaras, I take it you were able to find a resolution?

**Comment by Giintaras** [comment]
Hello, no I did not, but I figured I have installed way too many mods so obviously there are bound to be some conflicts, its a big misjudgement on my part wanting to have so many things in game.. Will try to discipline myself to reduce the amount of them significantly.
