### ISSUE TITLE
1.20.1 Chunk Generation Soft Brick

### ISSUE THREAD

**Issue by Landon-9999** [J-Dill/NoMoWanderer#20]
Hello! I'm from the team over at Nodecraft and noticed the version you mentioned in a previously closed issue is causing crashes (`nomowanderer-1.20.1-1.6.2.jar`)

Crash log below
[crash.txt](https://github.com/J-Dill/NoMoWanderer/files/13895019/crash.txt)

Removing the mod did allow for chunk generation past the specific chunk causing a server hang.

Can provide extra details if needed :)

**Comment by J-Dill** [comment]
@Landon-9999 Thanks for the report! This should now be fixed with the latest release for 1.20.1: https://legacy.curseforge.com/minecraft/mc-mods/nomowanderer/files/5038782
