### ISSUE TITLE
[Suggestion] Add support for blocking Plague Doctors from Rats mod

### ISSUE THREAD

**Issue by taj1994** [J-Dill/NoMoWanderer#4]
They're just a reskinned wandering trader with trades from the Rats mod, but seem to spawn more commonly than vanilla traders, making them even more annoying. Making the sign and totem work with them as well would be great

**Comment by J-Dill** [comment]
Hey @taj1994, yes I have definitely found them to be annoying as well in my last few days of playing some All the Mods. I will work on getting them added in as well!

Thanks for the suggestion!

**Comment by J-Dill** [comment]
@taj1994 In the latest release, v1.1, the Plague Doctor will now be treated just like the Wandering Trader and will be prevented from naturally spawning if the the same requirements are met to block the Wandering Trader from spawning.

So, closing issue. Thanks again for the suggestion, good one!
