### ISSUE TITLE
The 1.19 is marked as 1.18.2 game version. Is it a mistake or because it's compatible? :

### ISSUE THREAD

**Issue by Tomatoh** [J-Dill/NoMoWanderer#6]
Can you publish a new 1.18.2 so that the curse forge launcher doesnt keep trying to update the file to the 1.19 version? :)

**Comment by CKY-** [comment]
the 1.18.2 is using forge version 41 and marked as 1.19 
![image](https://user-images.githubusercontent.com/8982158/173707278-bf056279-ae9e-4cee-99cf-fd034e343914.png)

so it can't be updated in any packs that are 1.18.2

**Comment by Tomatoh** [comment]
yes but the curse launcher still shows it as a 1.18.2 mod so if you just publish a new one and upload it it should top that list

**Comment by J-Dill** [comment]
Interesting that CurseForge is still trying to get the 1.19 version of the mod even after it was marked as 1.19. Yes I can push a new version here to help fix that! Thanks for pointing it out.

**Comment by J-Dill** [comment]
I think this may have been because when I initially uploaded the first 1.19 version I had it accidentally marked as 1.18.2. I since changed it to be marked as 1.19, but this makes it look as if it didn't send out that update to the CurseForge client.

**Comment by J-Dill** [comment]
@Tomatoh A new 1.18.2 version has just been released. Let me know if that fixes the issue for ya

**Comment by Tomatoh** [comment]
Ah yes that fixed it!

**Comment by Tomatoh** [comment]
Issue fixed
