### ISSUE TITLE
Feature Request: Add default support for Supplementaries Red Merchant

### ISSUE THREAD

**Issue by SodiumShine** [J-Dill/NoMoWanderer#7]
I know you can just add it to the entityBlockList but I feel like it would go well with NoMoWanderer out of the box.
I believe the entity id is `supplementaries:red_merchant`

(If you haven't used Supplementaries, the red merchant is essentially the same as the wandering merchant, just sells explosives)

**Comment by J-Dill** [comment]
Yes, that sounds like an easy enough thing to add to the list by default! The current version of the mod I have not been able to get working, and it looks like others are having the same issue. So, I will be waiting until I can get the mod working and test it to add it as a default, but I like the idea!
